### ISSUE TITLE
Unable to apply data patch Magento\Theme\Setup\Patch\Data\RegisterThemes

### ISSUE THREAD

**Issue by Indre87** [MAD-I-T/magento-actions#20] opened 2022-04-03 10:05 UTC
Magento version 2.4.3-p1 fails on unit testing, static testing and build phase. 

In PatchApplier.php line 170:                                                                  
  Unable to apply data patch Magento\Theme\Setup\Patch\Data\RegisterThemes for module Magento_Theme. Original exception message: File "" does not exist.  
 In Gd2.php line 67:
 File "" does not exist.
 
 Seems to be related to this issue somehow? -> https://github.com/magento/magento2/issues/28055#issuecomment-622533641
 
 Any ideas?

**Comment by seyuf** [comment] 2022-04-03 17:05
Hi @Indre87 , can you share your main.yml or related file? Please?
This action uses a debian 9 image that should/could be run on top of a ubuntu container (see [here](https://github.com/seyuf/m2-dev-github-actions/blob/b57f6d0a42e611265716ab2b3b21a12cfc140eb2/.github/workflows/main.yml#L8) ).
As mentioned this issue seems to be related to windows environment, which is normally not supported (officially) by Magento.
Maybe using windows is a requirement for you. We may try to implement a fix in this action...

**Comment by Indre87** [comment] 2022-04-03 17:53
Hi! Sure, added main.yml to the bottom. I was also wondering how this issue came across since the images are linux and the bug was windows related. My environment is osx (local) and debian 9 (server). Magento build goes trough ok on both.

2 possibilities came to my mind.

1. The containers may set URLs to only "localhost". Magento code seems to check "$allowed_schemes = ['ftp', 'ftps', 'http', 'https'];". It could fail if no http/https are prefixed.

2. Containers have some settings missing for PHP using GD? 


Thanks for any help! 

main.yml

=====
name: m2-actions-test
on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    container: ubuntu
    name: 'm2 unit tests & build'
    services:
      mysql:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      elasticsearch:
        image: docker://elasticsearch:7.1.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
    - uses: actions/checkout@v1 # pulls your repository, M2 src must be in a magento directory
      with:
        submodules: recursive
    - name: 'this step will build an magento artifact'
      if: always()
      uses: MAD-I-T/magento-actions@v3.9
      env:
        COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
      with:
        php: '7.4'
        process: 'build'
        elasticsearch: 1
====

**Comment by seyuf** [comment] 2022-04-03 18:00
Great ima check this ASAP.
Also, we've been following the following thread since some days now.
https://github.com/magento/magento2/issues/34325

Best to avoid 2.4.3 and 2.4.3-p1, if you can, IMHO.
Anyway i'll try to reproduce the issue and keep you posted.

**Comment by Indre87** [comment] 2022-04-03 18:05
Thanks! Wow, good to know. Well, its best to avoid Magento overall if you can :D

**Comment by seyuf** [comment] 2022-04-03 18:24
Yeah, unfortunately the distrust is growing between magento and the OS community ^^.
Anyway, i just checked the php extension seems to be installed for php 7.4 (see [here](https://github.com/MAD-I-T/magento-actions/blob/master/Dockerfile#L81)).
Also, i just tried this [config](https://github.com/seyuf/test-m2-installer/blob/main/.github/workflows/main.yml), i'm having an old [fixed error](https://github.com/MAD-I-T/magento-actions/issues/11). Surely, there have been some regression regarding the later. Ima fix that asap. Can you try the linked config? And let me know if you still have the gd error?

**Comment by seyuf** [comment] 2022-04-03 18:29
![error-regression](https://user-images.githubusercontent.com/3765910/161442692-fb53c377-82ff-4762-829a-74a9c592f3bd.png)

**Comment by Indre87** [comment] 2022-04-03 18:49
Tried the config. No luck, got the same error. 

I noticed that the container uses composer 1.x? I'm using 2.x on local and server. Could that be the case?

**Comment by seyuf** [comment] 2022-04-03 19:05
Humm no the action automatically detects and enables the appropriate composer version according to the [magento doc](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html).
Have you removed the magento dir at the root of the project ? The config i linked will do fresh install before building. 
Also, you can force the composer version with `composer_version: 2` after the `with` argument, even though, im pretty sure that's not the issue, here. 
Can you also confirm taht you're using github runners ? Not a self-hosted one?

**Comment by seyuf** [comment] 2022-04-03 20:24
Just finished testing, as you can see [here](https://github.com/seyuf/test-m2-installer/actions) the build is successful with a fresh 2.4.3-p1 code regardless of the composer version (see commits associated to the last two action run). The [pagebuilder issue](https://github.com/MAD-I-T/magento-actions/issues/11) is solved by adding app/etc/config.php to the project git repo (nothing wrong with doing that).
I suspect your issue, have to do with your code. 
Let me know if you can reproduce it with a fresh 2.4.3-p1 install. You can also check your staic files for xml issues (job with static-test step).

**Comment by Indre87** [comment] 2022-04-04 07:28
Ok. Thx for ruling out the container. I need to figure out what causes this on my end. 5-star support from you 👍

**Comment by seyuf** [comment] 2022-04-04 07:45
You're welcome, feel free to close the issue whenever you're ready ;)

Regards

**Closed** 2022-04-04 09:30 UTC
Labels: bug, question
